### ISSUE TITLE
Permission fails on windows

### ISSUE THREAD

**Issue by laggingreflex** [leftstick/hosts-high#1]
First off, nice tool!

But I'm having permission issues on windows [10]. 

I've made sure to run it as admin but it still shows the error "Please make sure you have permission to modify etc/hosts" file

![](http://i.imgur.com/Z2RydBm.png)

Please feel free to let me know any way I can help debug.

**Comment by leftstick** [comment]
What version u r using? I believe `windows` is now supported in the latest version of `1.3.0`.

The version in `About Application` is pointed to `electron`, which is not the real app version. Can u have a try with latest download link?

I've only verified on `windows7`, this might also be the issue

**Comment by laggingreflex** [comment]
Ah, found the problem, it's a very odd thing I've done with my hosts file that I forgot about. I've moved it to my documents folder and created a hardlink to it back in /etc folder. (so it doesn't get lost upon reinstall). That's what was causing it. I created a new /etc/hosts file and it indeed worked.
